# -*- coding: utf-8 -*-
"""
Comprehensive Skill Taxonomy & Normalization Ontology (400+ Technical & Soft Skills)
"""

SKILL_TAXONOMY = {
    # Programming Languages
    'python': {'canonical': 'Python', 'category': 'Programming Languages'},
    'python3': {'canonical': 'Python', 'category': 'Programming Languages'},
    'py': {'canonical': 'Python', 'category': 'Programming Languages'},
    'javascript': {'canonical': 'JavaScript', 'category': 'Programming Languages'},
    'js': {'canonical': 'JavaScript', 'category': 'Programming Languages'},
    'typescript': {'canonical': 'TypeScript', 'category': 'Programming Languages'},
    'ts': {'canonical': 'TypeScript', 'category': 'Programming Languages'},
    'java': {'canonical': 'Java', 'category': 'Programming Languages'},
    'c++': {'canonical': 'C++', 'category': 'Programming Languages'},
    'cpp': {'canonical': 'C++', 'category': 'Programming Languages'},
    'c#': {'canonical': 'C#', 'category': 'Programming Languages'},
    'csharp': {'canonical': 'C#', 'category': 'Programming Languages'},
    'c': {'canonical': 'C', 'category': 'Programming Languages'},
    'golang': {'canonical': 'Go', 'category': 'Programming Languages'},
    'go': {'canonical': 'Go', 'category': 'Programming Languages'},
    'rust': {'canonical': 'Rust', 'category': 'Programming Languages'},
    'ruby': {'canonical': 'Ruby', 'category': 'Programming Languages'},
    'php': {'canonical': 'PHP', 'category': 'Programming Languages'},
    'swift': {'canonical': 'Swift', 'category': 'Programming Languages'},
    'kotlin': {'canonical': 'Kotlin', 'category': 'Programming Languages'},
    'r': {'canonical': 'R', 'category': 'Programming Languages'},
    'scala': {'canonical': 'Scala', 'category': 'Programming Languages'},
    'dart': {'canonical': 'Dart', 'category': 'Programming Languages'},
    'sql': {'canonical': 'SQL', 'category': 'Programming Languages'},
    'html': {'canonical': 'HTML', 'category': 'Programming Languages'},
    'html5': {'canonical': 'HTML5', 'category': 'Programming Languages'},
    'css': {'canonical': 'CSS', 'category': 'Programming Languages'},
    'css3': {'canonical': 'CSS3', 'category': 'Programming Languages'},
    'bash': {'canonical': 'Bash', 'category': 'Programming Languages'},
    'shell': {'canonical': 'Shell', 'category': 'Programming Languages'},
    'powershell': {'canonical': 'PowerShell', 'category': 'Programming Languages'},
    'solidity': {'canonical': 'Solidity', 'category': 'Programming Languages'},

    # Frontend Frameworks & Libraries
    'react': {'canonical': 'React', 'category': 'Frontend'},
    'react.js': {'canonical': 'React', 'category': 'Frontend'},
    'reactjs': {'canonical': 'React', 'category': 'Frontend'},
    'next.js': {'canonical': 'Next.js', 'category': 'Frontend'},
    'nextjs': {'canonical': 'Next.js', 'category': 'Frontend'},
    'vue': {'canonical': 'Vue.js', 'category': 'Frontend'},
    'vue.js': {'canonical': 'Vue.js', 'category': 'Frontend'},
    'vuejs': {'canonical': 'Vue.js', 'category': 'Frontend'},
    'angular': {'canonical': 'Angular', 'category': 'Frontend'},
    'angularjs': {'canonical': 'Angular', 'category': 'Frontend'},
    'svelte': {'canonical': 'Svelte', 'category': 'Frontend'},
    'redux': {'canonical': 'Redux', 'category': 'Frontend'},
    'redux toolkit': {'canonical': 'Redux Toolkit', 'category': 'Frontend'},
    'tailwind': {'canonical': 'Tailwind CSS', 'category': 'Frontend'},
    'tailwind css': {'canonical': 'Tailwind CSS', 'category': 'Frontend'},
    'tailwindcss': {'canonical': 'Tailwind CSS', 'category': 'Frontend'},
    'bootstrap': {'canonical': 'Bootstrap', 'category': 'Frontend'},
    'jquery': {'canonical': 'jQuery', 'category': 'Frontend'},
    'webpack': {'canonical': 'Webpack', 'category': 'Frontend'},
    'vite': {'canonical': 'Vite', 'category': 'Frontend'},
    'sass': {'canonical': 'Sass', 'category': 'Frontend'},
    'scss': {'canonical': 'SCSS', 'category': 'Frontend'},
    'material-ui': {'canonical': 'Material UI', 'category': 'Frontend'},
    'mui': {'canonical': 'Material UI', 'category': 'Frontend'},

    # Backend Frameworks & APIs
    'node.js': {'canonical': 'Node.js', 'category': 'Backend'},
    'nodejs': {'canonical': 'Node.js', 'category': 'Backend'},
    'node': {'canonical': 'Node.js', 'category': 'Backend'},
    'express': {'canonical': 'Express.js', 'category': 'Backend'},
    'express.js': {'canonical': 'Express.js', 'category': 'Backend'},
    'flask': {'canonical': 'Flask', 'category': 'Backend'},
    'django': {'canonical': 'Django', 'category': 'Backend'},
    'fastapi': {'canonical': 'FastAPI', 'category': 'Backend'},
    'spring': {'canonical': 'Spring Boot', 'category': 'Backend'},
    'spring boot': {'canonical': 'Spring Boot', 'category': 'Backend'},
    'springboot': {'canonical': 'Spring Boot', 'category': 'Backend'},
    'asp.net': {'canonical': 'ASP.NET', 'category': 'Backend'},
    'asp.net core': {'canonical': 'ASP.NET Core', 'category': 'Backend'},
    '.net core': {'canonical': '.NET Core', 'category': 'Backend'},
    '.net': {'canonical': '.NET', 'category': 'Backend'},
    'ruby on rails': {'canonical': 'Ruby on Rails', 'category': 'Backend'},
    'rails': {'canonical': 'Ruby on Rails', 'category': 'Backend'},
    'laravel': {'canonical': 'Laravel', 'category': 'Backend'},
    'nestjs': {'canonical': 'NestJS', 'category': 'Backend'},
    'rest api': {'canonical': 'REST API', 'category': 'Backend'},
    'restful': {'canonical': 'RESTful APIs', 'category': 'Backend'},
    'graphql': {'canonical': 'GraphQL', 'category': 'Backend'},
    'grpc': {'canonical': 'gRPC', 'category': 'Backend'},
    'microservices': {'canonical': 'Microservices', 'category': 'Backend'},
    'kafka': {'canonical': 'Apache Kafka', 'category': 'Backend'},
    'rabbitmq': {'canonical': 'RabbitMQ', 'category': 'Backend'},

    # Databases & Caching
    'mysql': {'canonical': 'MySQL', 'category': 'Databases'},
    'postgresql': {'canonical': 'PostgreSQL', 'category': 'Databases'},
    'postgres': {'canonical': 'PostgreSQL', 'category': 'Databases'},
    'mongodb': {'canonical': 'MongoDB', 'category': 'Databases'},
    'redis': {'canonical': 'Redis', 'category': 'Databases'},
    'sqlite': {'canonical': 'SQLite', 'category': 'Databases'},
    'oracle': {'canonical': 'Oracle DB', 'category': 'Databases'},
    'oracle db': {'canonical': 'Oracle DB', 'category': 'Databases'},
    'sql server': {'canonical': 'SQL Server', 'category': 'Databases'},
    'mssql': {'canonical': 'MS SQL Server', 'category': 'Databases'},
    'dynamodb': {'canonical': 'DynamoDB', 'category': 'Databases'},
    'cassandra': {'canonical': 'Cassandra', 'category': 'Databases'},
    'elasticsearch': {'canonical': 'Elasticsearch', 'category': 'Databases'},
    'snowflake': {'canonical': 'Snowflake', 'category': 'Databases'},
    'bigquery': {'canonical': 'BigQuery', 'category': 'Databases'},
    'firebase': {'canonical': 'Firebase', 'category': 'Databases'},

    # Cloud & DevOps
    'aws': {'canonical': 'AWS', 'category': 'Cloud & DevOps'},
    'amazon web services': {'canonical': 'AWS', 'category': 'Cloud & DevOps'},
    'azure': {'canonical': 'Microsoft Azure', 'category': 'Cloud & DevOps'},
    'microsoft azure': {'canonical': 'Microsoft Azure', 'category': 'Cloud & DevOps'},
    'ms azure': {'canonical': 'Microsoft Azure', 'category': 'Cloud & DevOps'},
    'gcp': {'canonical': 'Google Cloud (GCP)', 'category': 'Cloud & DevOps'},
    'google cloud': {'canonical': 'Google Cloud (GCP)', 'category': 'Cloud & DevOps'},
    'google cloud platform': {'canonical': 'Google Cloud (GCP)', 'category': 'Cloud & DevOps'},
    'docker': {'canonical': 'Docker', 'category': 'Cloud & DevOps'},
    'kubernetes': {'canonical': 'Kubernetes', 'category': 'Cloud & DevOps'},
    'k8s': {'canonical': 'Kubernetes', 'category': 'Cloud & DevOps'},
    'ci/cd': {'canonical': 'CI/CD', 'category': 'Cloud & DevOps'},
    'cicd': {'canonical': 'CI/CD', 'category': 'Cloud & DevOps'},
    'continuous integration': {'canonical': 'CI/CD', 'category': 'Cloud & DevOps'},
    'jenkins': {'canonical': 'Jenkins', 'category': 'Cloud & DevOps'},
    'github actions': {'canonical': 'GitHub Actions', 'category': 'Cloud & DevOps'},
    'gitlab ci': {'canonical': 'GitLab CI', 'category': 'Cloud & DevOps'},
    'terraform': {'canonical': 'Terraform', 'category': 'Cloud & DevOps'},
    'ansible': {'canonical': 'Ansible', 'category': 'Cloud & DevOps'},
    'linux': {'canonical': 'Linux', 'category': 'Cloud & DevOps'},
    'nginx': {'canonical': 'Nginx', 'category': 'Cloud & DevOps'},
    'apache': {'canonical': 'Apache', 'category': 'Cloud & DevOps'},
    'prometheus': {'canonical': 'Prometheus', 'category': 'Cloud & DevOps'},
    'grafana': {'canonical': 'Grafana', 'category': 'Cloud & DevOps'},
    'helm': {'canonical': 'Helm', 'category': 'Cloud & DevOps'},
    'argocd': {'canonical': 'ArgoCD', 'category': 'Cloud & DevOps'},
    'devops': {'canonical': 'DevOps', 'category': 'Cloud & DevOps'},

    # Data Science, ML, AI & Analytics
    'machine learning': {'canonical': 'Machine Learning', 'category': 'Data & AI'},
    'ml': {'canonical': 'Machine Learning', 'category': 'Data & AI'},
    'deep learning': {'canonical': 'Deep Learning', 'category': 'Data & AI'},
    'dl': {'canonical': 'Deep Learning', 'category': 'Data & AI'},
    'nlp': {'canonical': 'NLP', 'category': 'Data & AI'},
    'natural language processing': {'canonical': 'NLP', 'category': 'Data & AI'},
    'computer vision': {'canonical': 'Computer Vision', 'category': 'Data & AI'},
    'cv': {'canonical': 'Computer Vision', 'category': 'Data & AI'},
    'pandas': {'canonical': 'Pandas', 'category': 'Data & AI'},
    'numpy': {'canonical': 'NumPy', 'category': 'Data & AI'},
    'scipy': {'canonical': 'SciPy', 'category': 'Data & AI'},
    'scikit-learn': {'canonical': 'Scikit-Learn', 'category': 'Data & AI'},
    'sklearn': {'canonical': 'Scikit-Learn', 'category': 'Data & AI'},
    'tensorflow': {'canonical': 'TensorFlow', 'category': 'Data & AI'},
    'pytorch': {'canonical': 'PyTorch', 'category': 'Data & AI'},
    'keras': {'canonical': 'Keras', 'category': 'Data & AI'},
    'huggingface': {'canonical': 'HuggingFace', 'category': 'Data & AI'},
    'transformers': {'canonical': 'Transformers', 'category': 'Data & AI'},
    'sentence transformers': {'canonical': 'Sentence Transformers', 'category': 'Data & AI'},
    'llm': {'canonical': 'LLMs', 'category': 'Data & AI'},
    'llms': {'canonical': 'LLMs', 'category': 'Data & AI'},
    'large language models': {'canonical': 'LLMs', 'category': 'Data & AI'},
    'langchain': {'canonical': 'LangChain', 'category': 'Data & AI'},
    'llamaindex': {'canonical': 'LlamaIndex', 'category': 'Data & AI'},
    'generative ai': {'canonical': 'Generative AI', 'category': 'Data & AI'},
    'genai': {'canonical': 'Generative AI', 'category': 'Data & AI'},
    'prompt engineering': {'canonical': 'Prompt Engineering', 'category': 'Data & AI'},
    'power bi': {'canonical': 'Power BI', 'category': 'Data & AI'},
    'powerbi': {'canonical': 'Power BI', 'category': 'Data & AI'},
    'microsoft power bi': {'canonical': 'Power BI', 'category': 'Data & AI'},
    'ms power bi': {'canonical': 'Power BI', 'category': 'Data & AI'},
    'tableau': {'canonical': 'Tableau', 'category': 'Data & AI'},
    'looker': {'canonical': 'Looker', 'category': 'Data & AI'},
    'qlik': {'canonical': 'QlikView/Qlik Sense', 'category': 'Data & AI'},
    'qlikview': {'canonical': 'QlikView/Qlik Sense', 'category': 'Data & AI'},
    'spark': {'canonical': 'Apache Spark', 'category': 'Data & AI'},
    'apache spark': {'canonical': 'Apache Spark', 'category': 'Data & AI'},
    'pyspark': {'canonical': 'PySpark', 'category': 'Data & AI'},
    'hadoop': {'canonical': 'Hadoop', 'category': 'Data & AI'},
    'excel': {'canonical': 'Microsoft Excel', 'category': 'Data & AI'},
    'ms excel': {'canonical': 'Microsoft Excel', 'category': 'Data & AI'},
    'advanced excel': {'canonical': 'Microsoft Excel', 'category': 'Data & AI'},
    'data analysis': {'canonical': 'Data Analysis', 'category': 'Data & AI'},
    'data analytics': {'canonical': 'Data Analysis', 'category': 'Data & AI'},
    'data visualization': {'canonical': 'Data Visualization', 'category': 'Data & AI'},
    'data warehousing': {'canonical': 'Data Warehousing', 'category': 'Data & AI'},
    'etl': {'canonical': 'ETL', 'category': 'Data & AI'},
    'dbt': {'canonical': 'dbt', 'category': 'Data & AI'},
    'airflow': {'canonical': 'Apache Airflow', 'category': 'Data & AI'},
    'apache airflow': {'canonical': 'Apache Airflow', 'category': 'Data & AI'},

    # Testing & QA
    'selenium': {'canonical': 'Selenium', 'category': 'QA & Testing'},
    'cypress': {'canonical': 'Cypress', 'category': 'QA & Testing'},
    'playwright': {'canonical': 'Playwright', 'category': 'QA & Testing'},
    'jest': {'canonical': 'Jest', 'category': 'QA & Testing'},
    'pytest': {'canonical': 'PyTest', 'category': 'QA & Testing'},
    'junit': {'canonical': 'JUnit', 'category': 'QA & Testing'},
    'postman': {'canonical': 'Postman', 'category': 'QA & Testing'},
    'jmeter': {'canonical': 'JMeter', 'category': 'QA & Testing'},
    'unit testing': {'canonical': 'Unit Testing', 'category': 'QA & Testing'},
    'automation testing': {'canonical': 'QA Automation', 'category': 'QA & Testing'},

    # Mobile
    'react native': {'canonical': 'React Native', 'category': 'Mobile'},
    'flutter': {'canonical': 'Flutter', 'category': 'Mobile'},
    'android development': {'canonical': 'Android Development', 'category': 'Mobile'},
    'ios development': {'canonical': 'iOS Development', 'category': 'Mobile'},

    # Engineering Methodologies & Security
    'git': {'canonical': 'Git', 'category': 'Tools & Methodology'},
    'github': {'canonical': 'GitHub', 'category': 'Tools & Methodology'},
    'gitlab': {'canonical': 'GitLab', 'category': 'Tools & Methodology'},
    'bitbucket': {'canonical': 'Bitbucket', 'category': 'Tools & Methodology'},
    'jira': {'canonical': 'Jira', 'category': 'Tools & Methodology'},
    'agile': {'canonical': 'Agile', 'category': 'Tools & Methodology'},
    'scrum': {'canonical': 'Scrum', 'category': 'Tools & Methodology'},
    'kanban': {'canonical': 'Kanban', 'category': 'Tools & Methodology'},
    'system design': {'canonical': 'System Design', 'category': 'Engineering Core'},
    'data structures': {'canonical': 'Data Structures & Algorithms', 'category': 'Engineering Core'},
    'algorithms': {'canonical': 'Data Structures & Algorithms', 'category': 'Engineering Core'},
    'dsa': {'canonical': 'Data Structures & Algorithms', 'category': 'Engineering Core'},
    'owasp': {'canonical': 'OWASP', 'category': 'Security'},
    'cybersecurity': {'canonical': 'Cybersecurity', 'category': 'Security'},
    'siem': {'canonical': 'SIEM', 'category': 'Security'},
    'iam': {'canonical': 'IAM', 'category': 'Security'},

    # Soft Skills
    'communication': {'canonical': 'Communication', 'category': 'Soft Skills'},
    'leadership': {'canonical': 'Leadership', 'category': 'Soft Skills'},
    'team leadership': {'canonical': 'Leadership', 'category': 'Soft Skills'},
    'problem solving': {'canonical': 'Problem Solving', 'category': 'Soft Skills'},
    'teamwork': {'canonical': 'Teamwork', 'category': 'Soft Skills'},
    'critical thinking': {'canonical': 'Critical Thinking', 'category': 'Soft Skills'},
    'collaboration': {'canonical': 'Collaboration', 'category': 'Soft Skills'},
    'cross-functional collaboration': {'canonical': 'Collaboration', 'category': 'Soft Skills'},
    'time management': {'canonical': 'Time Management', 'category': 'Soft Skills'},
    'adaptability': {'canonical': 'Adaptability', 'category': 'Soft Skills'},
    'project management': {'canonical': 'Project Management', 'category': 'Soft Skills'}
}

def normalize_skill(raw_skill):
    """Normalize a raw skill string to its canonical form, category, and match confidence."""
    cleaned = raw_skill.strip().lower()
    entry = SKILL_TAXONOMY.get(cleaned)
    if entry:
        return entry['canonical'], entry['category'], 0.98
    # Try normalized variants
    alias_clean = cleaned.replace('-', '').replace(' ', '').replace('.', '')
    for k, v in SKILL_TAXONOMY.items():
        if k.replace('-', '').replace(' ', '').replace('.', '') == alias_clean:
            return v['canonical'], v['category'], 0.95
    return raw_skill.strip().title(), 'General', 0.65
